#!/usr/bin/env python3
"""Baseline test for step_supports.py.

Generates supports for test_model.step using the known-good inflation
algorithm and captures a data snapshot. Use this to compare against
when making changes to the support generation algorithm.

Usage:
    python3 tests/baseline.py                 # run tests and compare
    python3 tests/baseline.py --update        # update saved baseline
"""

import json
import os
import sys

import numpy as np
import trimesh

# Import from the WORKING version (root step_supports.py).
# The baseline snapshot was generated by the known-good inflation version
# (tests/baseline_generator.py) and should not be regenerated lightly.
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from step_supports import compute_supports, load_step

BASELINE_FILE = os.path.join(os.path.dirname(__file__), "baseline.json")
TEST_MODEL = os.path.join(os.path.dirname(os.path.dirname(__file__)), "models", "test_model.step")


def generate_snapshot(step_file: str) -> dict:
    """Generate a data snapshot of supports for a STEP file."""
    part, z_offset = load_step(step_file, verbose=False)
    supports = compute_supports(
        part, margin=0.2, min_volume=1.0, angle=45.0, verbose=False
    )

    if supports is None:
        return {"error": "no supports generated"}

    # Split into individual pieces
    pieces = supports.split(only_watertight=False)

    # Sort by volume descending for stable ordering
    pieces.sort(key=lambda p: -abs(p.volume))

    piece_data = []
    for i, piece in enumerate(pieces):
        bounds = piece.bounds
        piece_data.append({
            "index": i,
            "volume": round(abs(piece.volume), 1),
            "faces": len(piece.faces),
            "vertices": len(piece.vertices),
            "bounds_min": [round(float(x), 1) for x in bounds[0]],
            "bounds_max": [round(float(x), 1) for x in bounds[1]],
            "is_volume": piece.is_volume,
            "watertight": piece.is_watertight,
        })

    return {
        "model": os.path.basename(step_file),
        "total_pieces": len(pieces),
        "total_volume": round(abs(supports.volume), 1),
        "total_faces": len(supports.faces),
        "pieces": piece_data,
    }


def save_baseline(snapshot: dict):
    """Save snapshot as the baseline."""
    with open(BASELINE_FILE, "w") as f:
        json.dump(snapshot, f, indent=2)
    print(f"Baseline saved to {BASELINE_FILE}")


def load_baseline():
    """Load saved baseline."""
    if not os.path.exists(BASELINE_FILE):
        return None
    with open(BASELINE_FILE) as f:
        return json.load(f)


def compare(baseline: dict, current: dict) -> bool:
    """Compare current snapshot against baseline. Returns True if OK."""
    passed = True

    print(f"\n{'Metric':<25} {'Baseline':>12} {'Current':>12} {'Delta':>10} {'Status':>8}")
    print("-" * 70)

    # Total metrics
    for key, label in [
        ("total_pieces", "Pieces"),
        ("total_volume", "Volume (mm³)"),
        ("total_faces", "Faces"),
    ]:
        b = baseline[key]
        c = current[key]
        delta = c - b
        pct = (delta / b * 100) if b else 0

        # Pieces must match exactly; volume/faces allow 5% tolerance
        if key == "total_pieces":
            ok = b == c
        else:
            ok = abs(pct) < 5.0

        status = "✓" if ok else "✗ FAIL"
        if not ok:
            passed = False

        delta_str = f"{delta:+.1f}" if isinstance(delta, float) else f"{delta:+d}"
        print(f"  {label:<23} {b:>12} {c:>12} {delta_str:>10} {status:>8}")

    # Per-piece comparison (by sorted index)
    print(f"\n{'Piece':<8} {'Base Vol':>10} {'Curr Vol':>10} {'Delta%':>8} {'Status':>8}")
    print("-" * 50)

    max_pieces = max(len(baseline["pieces"]), len(current["pieces"]))
    for i in range(max_pieces):
        bp = baseline["pieces"][i] if i < len(baseline["pieces"]) else None
        cp = current["pieces"][i] if i < len(current["pieces"]) else None

        if bp and cp:
            bv = bp["volume"]
            cv = cp["volume"]
            pct = ((cv - bv) / bv * 100) if bv else 0
            ok = abs(pct) < 10.0
            if not ok:
                passed = False
            status = "✓" if ok else "✗"
            print(f"  {i:<6} {bv:>10.1f} {cv:>10.1f} {pct:>+7.1f}% {status:>8}")
        elif bp:
            print(f"  {i:<6} {bp['volume']:>10.1f} {'MISSING':>10} {'':>8} {'✗':>8}")
            passed = False
        else:
            print(f"  {i:<6} {'NEW':>10} {cp['volume']:>10.1f} {'':>8} {'✗':>8}")
            passed = False

    return passed


def main():
    if not os.path.exists(TEST_MODEL):
        print(f"Error: {TEST_MODEL} not found")
        sys.exit(1)

    update = "--update" in sys.argv

    print(f"Generating supports for {os.path.basename(TEST_MODEL)}...")
    current = generate_snapshot(TEST_MODEL)
    print(f"  {current['total_pieces']} pieces, "
          f"{current['total_volume']:.1f} mm³, "
          f"{current['total_faces']} faces")

    if update:
        save_baseline(current)
        return

    if "--generate-stl" in sys.argv:
        # Generate the clean baseline STL using the inflation algorithm
        sys.path.insert(0, os.path.dirname(__file__))
        from baseline_generator import compute_supports as baseline_compute, load_step as baseline_load
        print("Generating baseline STL from inflation algorithm...")
        bpart, bz = baseline_load(TEST_MODEL, verbose=True)
        bsupports = baseline_compute(bpart, margin=0.2, min_volume=1.0, angle=45.0, verbose=True)
        if bsupports is not None:
            if abs(bz) > 1e-6:
                bsupports.apply_translation([0, 0, bz])
            out = os.path.join(os.path.dirname(__file__), "test_model_supports.stl")
            bsupports.export(out)
            print(f"Baseline supports written to {out}")
        return

    baseline = load_baseline()
    if baseline is None:
        print("\nNo baseline found. Creating one...")
        save_baseline(current)
        print("Run again to compare against this baseline.")
        return

    passed = compare(baseline, current)
    print()
    if passed:
        print("✓ All checks passed")
    else:
        print("✗ Some checks failed — review changes")
        sys.exit(1)


if __name__ == "__main__":
    main()
